# Generated by Django 2.2.4 on 2019-08-29 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents_pdfs')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_head', models.CharField(max_length=100)),
                ('legal_name', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='news_images')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
