# Generated by Django 2.2.4 on 2019-08-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='legal_name',
            new_name='post_text',
        ),
    ]
