# Generated by Django 2.2.4 on 2019-08-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skSite', '0002_auto_20190829_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='owner',
            new_name='doc_name',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_description',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
