# Generated by Django 2.2.4 on 2019-08-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skSite', '0003_auto_20190831_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_text', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='slider_img')),
            ],
        ),
    ]
