# Generated by Django 2.2.4 on 2019-10-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skSite', '0004_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='file',
            field=models.ImageField(default='default.jpg', upload_to='slider_img'),
        ),
    ]
