# Generated by Django 2.2.4 on 2019-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skSite', '0005_auto_20191001_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(max_length=3000),
        ),
    ]
