# Generated by Django 2.2.4 on 2019-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skSite', '0006_auto_20191001_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_short_body',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_head',
            field=models.CharField(max_length=128),
        ),
    ]
