# Generated by Django 2.2.4 on 2019-10-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skSite', '0007_auto_20191002_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telegram', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=2000)),
            ],
        ),
    ]
